name: Backport PR

# Description:
#   Automates the creation of backport pull requests to target branches.
#   This is a reusable workflow designed to be called by a parent workflow
#   and triggered usually triggered on a PR merge.
#
# Inputs:
#   - GH_TOKEN: A GitHub PAT with repo and workflow scopes.
#   - GPG_PRIVATE_KEY: The exported GPG private key used to sign backport commits.
#   - GPG_PASSPHRASE: The passphrase for the provided GPG key.

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  backport-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Create backport pull requests
        uses: mvlassis/backport-action@add-all-reviewers-input
        with:
          copy_assignees: true
          copy_all_reviewers: true
          copy_requested_reviewers: true
          pull_title: "${pull_title} (backport #${pull_number})"
          github_token: ${{ secrets.GH_TOKEN }}
          experimental: '{"conflict_resolution": "draft_commit_conflicts"}'
